admin_app/urls.py
from django.urls import path
from . import views

app_name = "admin_app"

from . import views
from rest_framework import routers
from django.urls import path, include


urlpatterns = [

    #onion api
    
    path('confirm-payment/', views.ConfirmPaymentView, name="confirm_payment"),
    
    path('', views.SignInView, name="sign_in"),
    path('sign-out/', views.SignOutView, name="sign_out"),
    
    path('index/', views.IndexView, name="index"),
    
    path('all-categories/', views.AllCategoriesView, name="all_categories"),
    path('category-detail/<int:category_id>/', views.CategoryDetailView, name="category_detail"),
    path('delete/category/<int:category_id>/', views.DeleteCategoryView, name="delete_category"),



    path('all-problems/', views.AllProblemsView, name="all_problems"),
    path('problem-detail/<int:problem_id>/', views.ProblemDetailView, name="problem_detail"),

    path('all-problems/', views.AllProblemsView, name="all_problems"),
    path('problem-detail/<int:problem_id>/', views.ProblemDetailView, name="problem_detail"),

    path('all-reported-videos/', views.ReportedVideosView, name="reported_videos"),

    path('reported-problem-detail/<int:problem_id>/', views.ReportPDetailView, name="reported_p_detail"),
    path('reported-solution-detail/<int:solution_id>/', views.ReportSDetailView, name="reported_s_detail"),

    path('all-users/', views.AllUsersView, name="all_users"),
    path('user-detail/<int:user_id>/', views.UserDetailView, name="user_detail"),

    path('approve-solution/<int:solution_id>/', views.ApproveSolutionView, name="approve_solution"),
    path('approve-user/<int:app_user_id>/', views.ApproveUserView, name="approve_user"),
    path('approve-problem/<int:problem_id>/', views.ApproveProblemView, name="approve_problem"),

]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

from . import views
from rest_framework import routers
from django.urls import path, include


urlpatterns = [
    
    #landing page
    path('', views.IndexView, name="index"),
    path('privacy-policy/', views.PrivacyView, name="privacy"),
    path('contact', views.ContactView, name="contact"),
    path('faq/', views.FaqView, name="faq"),

    #onion api
    path('sign-up/', views.SignUpView),
    path('sign-in/', views.SignInView),

    path('get-appuser/<str:auth_code>/', views.ACGetAppUserView),
    path('edit-appuser/', views.EditAppUserView),

    path('add-problem/', views.AddProblemView),
    path('edit-problem/', views.EditProblemView),
    path('add-solution/', views.AddSolutionView),

    path('set-payment/', views.SetPaymentView),

    path('get-user-problems/<str:auth_code>/', views.GetUserProblemsView),
    path('get-user-solutions/<str:auth_code>/', views.GetUserSolutionsView),
    path('get-problem-solutions/<int:problem_id>/', views.GetProblemSolutionsView),

    path('get-all-problems/', views.GetAllProblemsView),
    path('get-all-solutions/', views.GetAllSolutionsView),
    
    path('get-problem-detail/<str:auth_code>/<int:problem_id>/', views.GetProblemDetailView),
    path('get-solution-detail/<str:auth_code>/<int:solution_id>/', views.GetSolutionDetailView),

    path('problem/add-clap/', views.AddProblemClapView),
    path('problem/add-buzz/', views.AddProblemBuzzView),
    path('problem/add-comment/', views.AddPCommentView),
    path('problem/get-comments/<int:problem_id>/', views.GetPCommentView),

    path('problem/report/', views.ReportProblemView),
    path('solution/report/', views.ReportSolutionView),

    path('solution/add-clap/', views.AddSolutionClapView),
    path('solution/add-buzz/', views.AddSolutionBuzzView),
    path('solution/add-comment/', views.AddSCommentView),
    path('solution/get-comments/<int:solution_id>/', views.GetSCommentView),

    path('problem/add-rating/', views.RateProblemView),
    path('solution/add-rating/', views.RateSolutionView),

    path('appuser/request/new-password/', views.RequestNewPwView),
    path('appuser/set/new-password/', views.SetNewPwView),
    path('appuser/activate/', views.ActivateUserView),

    path('get-all-tags/', views.GetAllTagView),
    path('get-all-categories/', views.GetAllCategoriesView),
    
    
    path('find-all-problems/tag/', views.FindAllProblemsTView),
    path('find-all-problems/category/', views.FindAllProblemsCView),
    path('find-all-problems/title/', views.FindAllProblemsTiView),
    
    path('get-timeline/', views.GetTimelineView),
    path('get-notifications/<str:auth_code>/', views.GetAppUserNotificationView),

    path('analytics/video-rating/', views.AnalyticsVRView),
    path('analytics/views/', views.AnalyticsVView),
    path('analytics/total-videos/', views.AnalyticsTVView),

    path('analytics/video-rating/<str:auth_code>/', views.AnalyticsUVRView),
    path('analytics/views/<str:auth_code>/', views.AnalyticsUVView),
    path('analytics/total-videos/<str:auth_code>/', views.AnalyticsUTVView),


]

onion_api/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("admin-app/", include("admin_app.urls")),
    path("app/", include("app_user.urls")),



]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin_app/models.py
from django.db import models

# Create your models here.

admin_app/views.py
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from main.models import *

# Create your views here.





def ConfirmPaymentView(request):
	

	if request.method == "POST":
		username = request.POST.get("username")

		try:
			app_user = AppUser.objects.get(user__username=username)
			app_user.payment_status = True
			app_user.save()

			return HttpResponse("Payment confirmed, returning back to app.")

		except:
			return HttpResponse("Sorry there was an issue, returning back to app.")


		
	else:

		context = {
		}

		return render(request, "admin_app/confirm_payment.html", context)


def SignInView(request):

	if request.method == "POST":

		username = request.POST.get("username")
		password = request.POST.get("password")


		user = authenticate(username=username, password=password)

		if user:
			if user.is_active and user.is_superuser:
				login(request, user)
				return HttpResponseRedirect(reverse("admin_app:index"))


			else:
				context = {"msg": "Sorry, you are not at admin."}
				return render(request, "admin_app/sign_in.html", context)

		else:
			context = {"msg": "Sorry, invalid logins."}
			return render(request, "admin_app/sign_in.html", context)


				
	else:

		context = {}
		return render(request, "admin_app/sign_in.html", context)




def SignOutView(request):
	logout(request)

	return HttpResponseRedirect(reverse("admin_app:sign_in"))




def AllCategoriesView(request):
	categories = Category.objects.order_by("-pub_date")
	if request.method == "POST":

		name = request.POST.get("name")

		category = Category.objects.create(name=name)
		category.save()

		return HttpResponseRedirect(reverse("admin_app:all_categories"))

		

		
	else:
		context = {
		"categories": categories
		}

		return render(request, "admin_app/all_categories.html", context)




def CategoryDetailView(request, category_id):
	category = Category.objects.get(id=category_id)
	if request.method == "POST":
		new_name = request.POST.get("new_name")
		category.name = new_name
		category.save()

		return HttpResponseRedirect(reverse("admin_app:all_categories"))
		
	else:

		context = {
		"category": category
		}

		return render(request, "admin_app/category_detail.html", context)




def DeleteCategoryView(request, category_id):
	category = Category.objects.get(id=category_id)
	if request.method == "POST":
		category = Category.objects.get(id=category_id)
		category.delete()

		return HttpResponseRedirect(reverse("admin_app:all_categories"))

		
	else:
		context = {
		"category": category
		}

		return render(request, "admin_app/delete_category.html", context)
		

		


def IndexView(request):

	if request.method == "POST":
		pass

		
	else:

		try:
			user = User.objects.get(pk=request.user.id)
			if user.is_superuser:

				app_users = AppUser.objects.all()
				problems = Problem.objects.all()
				solutions = Solution.objects.all()
				approved_solutions = Solution.objects.filter(status=True)

				latest_problems = problems[:10]
				latest_users = app_users[:10]
				latest_solution_video = solutions[:10]


				context = {
					"app_users": app_users,
					"problems": problems,
					"solutions": solutions,
					"approved_solutions": approved_solutions,

					"latest_problems": latest_problems,
					"latest_users": latest_users,
					"latest_solution_video": latest_solution_video,

				}

				return render(request, "admin_app/index.html", context)


			else:
				return HttpResponseRedirect(reverse("admin_app:sign_out"))

		except:
			return HttpResponseRedirect(reverse("admin_app:sign_out"))


def AllProblemsView(request):

	if request.method == "POST":
		pass

		
	else:

		problems = Problem.objects.all().order_by("-pub_date")

		context = {
		"problems": problems
		}

		return render(request, "admin_app/all_problems.html", context)




def ReportedVideosView(request):

	if request.method == "POST":
		pass

		
	else:

		problems = Problem.objects.all().order_by("-pub_date")
		solutions = Solution.objects.all().order_by("-pub_date")

		reported_p_videos = []
		reported_s_videos = []

		for item in problems:
			if item.report_count > 0:
				reported_p_videos.append(item)

		for item in solutions:
			if item.report_count > 0:
				reported_s_videos.append(item)


		

		context = {
		"reported_p_videos": reported_p_videos,
		"reported_s_videos": reported_s_videos

		}

		return render(request, "admin_app/reported_videos.html", context)


def ReportPDetailView(request, problem_id):

	if request.method == "POST":
		pass

		
	else:
		problem = Problem.objects.get(id=problem_id)
		reports = problem.reports.all()

		context = {
			"problem": problem, 
			"reports": reports,
			}

		return render(request, "admin_app/report_p_detail.html", context)



def ReportSDetailView(request, solution_id):

	if request.method == "POST":
		pass

		
	else:
		solution = Solution.objects.get(id=solution_id)
		reports = solution.reports.all()

		context = {
			"solution": solution, 
			"reports": reports,
			}

		return render(request, "admin_app/report_s_detail.html", context)






def ProblemDetailView(request, problem_id):

	if request.method == "POST":
		pass

		
	else:
		problem = Problem.objects.get(id=problem_id)
		solutions = Solution.objects.filter(problem__id=problem_id)

		context = {
			"problem": problem, 
			"solutions": solutions,
			}

		return render(request, "admin_app/problem_detail.html", context)



def AllUsersView(request):

	if request.method == "POST":
		pass

		
	else:

		app_users = AppUser.objects.all().order_by("-pub_date")

		context = {
			"app_users": app_users,
		}

		return render(request, "admin_app/all_users.html", context)


def UserDetailView(request, user_id):

	if request.method == "POST":
		pass

		
	else:

		context = {}
		return render(request, "admin_app/user_detail.html", context)





def ApproveSolutionView(request, solution_id):
	if request.method == "POST":

		solution = Solution.objects.get(id=solution_id)
		problem_id = solution.problem.id

		if solution.status == True:
			solution.status = False

		else:
			solution.status = True

		solution.save()
		
		nt = Notification.objects.create(app_user=solution.app_user, detail="Your solution video for (%s) have been approved!" % (solution.title), object_id="None")
		nt.save()

		return HttpResponseRedirect(reverse("admin_app:problem_detail", args=[problem_id,]))



	else:
		pass



def ApproveUserView(request, app_user_id):
	if request.method == "POST":

		app_user = AppUser.objects.get(id=app_user_id)

		if app_user.status == True:
			app_user.status = False

		else:
			app_user.status = True

		app_user.save()

		return HttpResponseRedirect(reverse("admin_app:all_users"))



	else:
		pass	




def ApproveProblemView(request, problem_id):
	if request.method == "POST":

		problem = Problem.objects.get(id=problem_id)

		if problem.status == True:
			problem.status = False

		else:
			problem.status = True

		problem.save()
		
		nt = Notification.objects.create(app_user=problem.app_user, detail="Your problem video (%s) has been approved!" % (problem.title), object_id="None")
		nt.save()
				

		app_users = AppUser.objects.all()
		for item in app_users:
			if item.interest == problem.category:
				nt2 = Notification.objects.create(app_user=item, detail="New Problem Alert! (%s)" % (problem.title), object_id="None")
				nt2.save()

		return HttpResponseRedirect(reverse("admin_app:problem_detail", args=[problem_id,]))




	else:
		pass	

admin_app/templates/admin_app/all_categories.html
{% extends 'admin_app/base.html' %}
{% load static %}


{% block content %}



<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Categories</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Categories</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>


<section class="content">
    <div class="container-fluid">


      <div class="row">
        <form class="form-group" method="post">
            {% csrf_token %}
            <input class="form-control" type="text" name="name" placeholder="Enter Category Name">
            <br />
            <button class="form-control">Add New Categories</button>
        </form>

      </div>
      <br /><br />

      <div class="row">
          <div class="col-12">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">All Categories</h3>

              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap container">
                  <thead>
                    <tr>
                        <th>Names</th>
                        <th>Creators</th>
                        <th>Dates</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in categories %}
                        <tr>
                            <td>{{ item.name }}</td>
                            <td>{{ item.creator }}</td>
                            <td>{{ item.pub_date }}</td>

                            <td><a class="btn btn-primary" href="{% url 'admin_app:category_detail' item.id %}">Edit</a> </td>
                            <td><a class="btn btn-primary" href="{% url 'admin_app:delete_category' item.id %}">Delete</a> </td>
                            <td></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

</div>

{% endblock content %}

admin_app/templates/admin_app/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css'%} ">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet"
        href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'%} ">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css'%} ">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css'%} ">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'%} ">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css'%} ">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css'%} ">
    <!-- summernote -->
    <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.css'%} ">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="index3.html" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link">Logout</a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Messages Dropdown Menu -->
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="{% static 'dist/img/AdminLTELogo.png' %} " alt="AdminLTE Logo"
                    class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Onion App</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="info">
                        <a href="#" class="d-block">Admin Dashboard</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href="{% url 'admin_app:index' %}" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Dashboard
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                        </li>

                         <li class="nav-item has-treeview menu-open">
                            <a href="{% url 'admin_app:all_categories' %}" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    All Categories
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                        </li>

                        <li class="nav-item has-treeview menu-open">
                            <a href="{% url 'admin_app:all_users' %}" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    All Users
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                        </li>

                        <li class="nav-item has-treeview menu-open">
                            <a href="{% url 'admin_app:all_problems' %}" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    All Problems
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                        </li>

                        <li class="nav-item has-treeview menu-open">
                            <a href="{% url 'admin_app:sign_out' %}" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                Logout
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                        </li>

                        <li class="nav-item">
                            <a href="{% url 'admin_app:reported_videos' %}" class="nav-link">
                                <i class="nav-icon far fa-circle text-danger"></i>
                                <p class="text">Reported Videos</p>
                            </a>
                        </li>

                        
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-circle text-warning"></i>
                                <p>How it works</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-circle text-danger"></i>
                                <p class="text">About</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-circle text-info"></i>
                                <p>Learn more</p>
                            </a>
                        </li>

                         



                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>



        {% block content %}


        {% endblock %}

        
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2021 <a href="#">Onion App</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 1.00
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js'%} "></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js'%} "></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%} "></script>
    <!-- ChartJS -->
    <script src="{% static 'plugins/chart.js/Chart.min.js'%} "></script>
    <!-- Sparkline -->
    <script src="{% static 'plugins/sparklines/sparkline.js'%} "></script>
    <!-- JQVMap -->
    <script src="{% static 'plugins/jqvmap/jquery.vmap.min.js'%} "></script>
    <script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js'%} "></script>
    <!-- jQuery Knob Chart -->
    <script src="{% static 'plugins/jquery-knob/jquery.knob.min.js'%} "></script>
    <!-- daterangepicker -->
    <script src="{% static 'plugins/moment/moment.min.js'%} "></script>
    <script src="{% static 'plugins/daterangepicker/daterangepicker.js'%} "></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js'%} "></script>
    <!-- Summernote -->
    <script src="{% static 'plugins/summernote/summernote-bs4.min.js'%} "></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js'%} "></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.js'%} "></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'dist/js/pages/dashboard.js'%} "></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js'%} "></script>
</body>

</html>

admin_app/templates/admin_app/category_detail.html
{% extends 'admin_app/base.html' %}
{% load static %}


{% block content %}



<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Edit Category</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Edit Category</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>


<section class="content">
    <div class="container-fluid">


      <div class="row">
        <form class="form-group" method="post">
            {% csrf_token %}
            <input class="form-control" type="text" name="new_name" value="{{ category.name }}">
            <br />
            <button class="form-control">Update</button>
        </form>

      </div>
      <br /><br />

      
    </div>
</section>

</div>

{% endblock content %}

admin_app/templates/admin_app/reported_videos.html
{% extends 'admin_app/base.html' %}
{% load static %}


{% block content %}



<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">All Reported Videos</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">All Reported Videos</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>


<section class="content">
    <div class="container-fluid">
      <div class="row">
          <div class="col-6">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">From Problems</h3>

              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap container">
                  <thead>
                    <tr>
                        <th>Title</th>
                        <th>Date</th>
                        <th>Action</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in reported_p_videos %}
                        <tr>
                            <td>{{ item.title }}</td>
                            <td>{{ item.pub_date }}</td>
                            <td><a class="btn btn-primary" href="{% url 'admin_app:reported_p_detail' item.id %}">Details</a> </td>
                            <td></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                    </div>
                </div>

            </div>



            <div class="col-6">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">All Solutions</h3>

              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap container">
                  <thead>
                    <tr>
                        <th>Title</th>
                        <th>Date</th>
                        <th>Action</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in reported_s_videos %}
                        <tr>
                            <td>{{ item.title }}</td>
                            <td>{{ item.pub_date }}</td>
                            <td><a class="btn btn-primary" href="{% url 'admin_app:reported_s_detail' item.id %}">Details</a> </td>
                            <td></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                    </div>
                </div>

            </div>












        </div>
    </div>
</section>

</div>

{% endblock content %}