app_user/urls.py
from django.urls import path
from . import views

app_name = "app_user"

from . import views
from rest_framework import routers
from django.urls import path, include


urlpatterns = [

    path('sign-in/', views.SignInView, name="sign_in"),
    path('sign-up/', views.SignUpView, name="sign_up"),
    path('email-verify/', views.EmailVerifyView, name="email_verify"),
    path('sign-out/', views.SignOutView, name="sign_out"),
    
    path('', views.IndexView, name="index"),
    path('profile/', views.ProfileView, name="profile"),
    path('notifications/', views.NotificationsView, name="notifications"),
    path('timeline/', views.TimelineView, name="timeline"),

    path('clap-solution/<int:solution_id>/', views.ClapSolutionView, name="clap_solution"),
    path('buzz-solution/<int:solution_id>/', views.BuzzSolutionView, name="buzz_solution"),

    path('notify/<str:msg>/', views.NotifyView, name="notify"),

    path('add-problem/', views.AddProblemView, name="add_problem"),
    path('problem-detail/<int:problem_id>/', views.ProblemDetailView, name="problem_detail"),

]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

from . import views
from rest_framework import routers
from django.urls import path, include


urlpatterns = [
    
    #landing page
    path('', views.IndexView, name="index"),
    path('privacy-policy/', views.PrivacyView, name="privacy"),
    path('contact', views.ContactView, name="contact"),
    path('faq/', views.FaqView, name="faq"),

    #onion api
    path('sign-up/', views.SignUpView),
    path('sign-in/', views.SignInView),

    path('get-appuser/<str:auth_code>/', views.ACGetAppUserView),
    path('edit-appuser/', views.EditAppUserView),

    path('add-problem/', views.AddProblemView),
    path('edit-problem/', views.EditProblemView),
    path('add-solution/', views.AddSolutionView),

    path('set-payment/', views.SetPaymentView),

    path('get-user-problems/<str:auth_code>/', views.GetUserProblemsView),
    path('get-user-solutions/<str:auth_code>/', views.GetUserSolutionsView),
    path('get-problem-solutions/<int:problem_id>/', views.GetProblemSolutionsView),

    path('get-all-problems/', views.GetAllProblemsView),
    path('get-all-solutions/', views.GetAllSolutionsView),
    
    path('get-problem-detail/<str:auth_code>/<int:problem_id>/', views.GetProblemDetailView),
    path('get-solution-detail/<str:auth_code>/<int:solution_id>/', views.GetSolutionDetailView),

    path('problem/add-clap/', views.AddProblemClapView),
    path('problem/add-buzz/', views.AddProblemBuzzView),
    path('problem/add-comment/', views.AddPCommentView),
    path('problem/get-comments/<int:problem_id>/', views.GetPCommentView),

    path('problem/report/', views.ReportProblemView),
    path('solution/report/', views.ReportSolutionView),

    path('solution/add-clap/', views.AddSolutionClapView),
    path('solution/add-buzz/', views.AddSolutionBuzzView),
    path('solution/add-comment/', views.AddSCommentView),
    path('solution/get-comments/<int:solution_id>/', views.GetSCommentView),

    path('problem/add-rating/', views.RateProblemView),
    path('solution/add-rating/', views.RateSolutionView),

    path('appuser/request/new-password/', views.RequestNewPwView),
    path('appuser/set/new-password/', views.SetNewPwView),
    path('appuser/activate/', views.ActivateUserView),

    path('get-all-tags/', views.GetAllTagView),
    path('get-all-categories/', views.GetAllCategoriesView),
    
    
    path('find-all-problems/tag/', views.FindAllProblemsTView),
    path('find-all-problems/category/', views.FindAllProblemsCView),
    path('find-all-problems/title/', views.FindAllProblemsTiView),
    
    path('get-timeline/', views.GetTimelineView),
    path('get-notifications/<str:auth_code>/', views.GetAppUserNotificationView),

    path('analytics/video-rating/', views.AnalyticsVRView),
    path('analytics/views/', views.AnalyticsVView),
    path('analytics/total-videos/', views.AnalyticsTVView),

    path('analytics/video-rating/<str:auth_code>/', views.AnalyticsUVRView),
    path('analytics/views/<str:auth_code>/', views.AnalyticsUVView),
    path('analytics/total-videos/<str:auth_code>/', views.AnalyticsUTVView),


]

onion_api/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("admin-app/", include("admin_app.urls")),
    path("app/", include("app_user.urls")),



]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app_user/models.py
from django.db import models

# Create your models here.

app_user/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password1 = forms.CharField(widget=forms.PasswordInput())
	password2 = forms.CharField(widget=forms.PasswordInput())
	class Meta():
		model = User
		fields = ("username", "password1", "password2")

app_user/views.py
from django.contrib import messages
from django.shortcuts import (HttpResponse, HttpResponseRedirect, get_object_or_404, redirect, render)
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from django.utils import timezone
import datetime

from main.models import *
import requests
from app_user.forms import *

import random
import string


from django.core.mail import send_mail
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from django.db.models import Q




def RaySendMail(subject, message, to_email, code=None):

    try:
        context = {"subject": subject, "message": message, "code": code}
        html_message = render_to_string('main/message.html', context)
        message = strip_tags(message)
    
        send_mail(
            subject,
            message,
            'hello@helloonions.com',
            [to_email,],
            html_message=html_message,
            fail_silently=False,
        )

    except:
        pass




def ray_randomiser(length=12):
	landd = string.ascii_letters + string.digits
	return ''.join((random.choice(landd) for i in range(length)))


def SignInView(request):
	if request.method == "POST":
		username = request.POST.get("username")
		password = request.POST.get("password")
		user = authenticate(username=username, password=password)
		if user:
			if user.is_active:
				login(request, user)

				app_user = AppUser.objects.get(user__pk=request.user.id)

				print("11111111111111111111111111111111")
				messages.success(request, "Welcome Onboard")
				return HttpResponseRedirect(reverse("app_user:index"))


			else:
				print("22222222222222222222222222222222")
				messages.warning(request, "Sorry, Invalid Login Details")
				return HttpResponseRedirect(reverse("app_user:sign_in"))

		else:
			print("33333333333333333333333333333333333333")
			messages.warning(request, "Sorry, Invalid Login Details")
			return HttpResponseRedirect(reverse("app_user:sign_in"))

	else:
		context = {}
		return render(request, "app_user/sign_in.html", context )




def SignUpView(request):
	if request.method == "POST":

		form = UserForm(request.POST or None, request.FILES or None)
		email = request.POST.get("username")
		password1 = request.POST.get("password1")
		password2 = request.POST.get("password2")

		first_name = request.POST.get("first_name")
		last_name = request.POST.get("last_name")
		interest = request.POST.get("interest")

		request.session.create()
		auth_code = request.session.session_key

		app_users = AppUser.objects.filter(user__username=request.POST.get("username"))

		if request.POST.get("password2") != request.POST.get("password1"):
			messages.warning(request, "Make sure both passwords match")
			print("passwords didn't match")
			return HttpResponseRedirect(reverse("app_user:sign_up"))

		elif len(app_users) > 0:
			messages.warning(request, "Email Address already taken, try another one!")
			print("email address already taken")
			return HttpResponseRedirect(reverse("app_user:sign_up"))
			
		else:
			user = form.save()
			user.set_password(request.POST.get("password1"))
			user.save()

			app_user = AppUser.objects.create(user=user, first_name=first_name, last_name=last_name,
				interest=interest, email=user.username, auth_code=auth_code)
				
			request_code = ray_randomiser()
			app_user.request_code = request_code
			app_user.save()

			RaySendMail("Authentication", "Welcome to Onions, Please use the authentication code below to complete your sign up!", app_user.user.username, code=request_code)

			nt = Notification.objects.create(app_user=app_user, detail="Welcome to ONIONS", object_id="None")
			nt.save()

			if user:
				if user.is_active:
					login(request, user)

					app_user = AppUser.objects.get(user__pk=request.user.id)
					return HttpResponseRedirect(reverse("app_user:email_verify"))


	else:
		categories = Category.objects.all().order_by("-pub_date")
		form = UserForm()

		context = {"form": form, "categories": categories}
		return render(request, "app_user/sign_up.html", context )




def EmailVerifyView(request):

	app_user = AppUser.objects.get(user__pk=request.user.id)
	if request.method == "POST":
		auth_code = request.POST.get("auth_code")
		if auth_code == app_user.request_code:
			return HttpResponseRedirect(reverse("app_user:index"))

		else:
			msg = "Sorry, Invalid Auth Code."
			
			context = {"app_user": app_user, "msg": msg}
			return render(request, "app_user/email_verify.html", context)
			



	else:
		timelines = requests.post("https://helloonions.com/get-timeline/")
		timelines = timelines.json()

		context = {"app_user": app_user, "timelines": timelines}
		return render(request, "app_user/email_verify.html", context)




def SignOutView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	if request.method == "POST":
		pass


	else:
		timeline = []

		context = {"app_user": app_user, "timeline": timeline}
		return render(request, "app_user/timeline.html", context)






def IndexView(request):
	#needed objects
	try:
		app_user = AppUser.objects.get(user__pk=request.user.id)

	except:
		app_user = None

	categories = Category.objects.all().order_by('-pub_date')


	#app_user = None
	if request.method == "POST":
		pass


	else:
		problems = Problem.objects.filter(status=True).order_by('-pub_date')
		solutions = Solution.objects.filter(status=True).order_by('-pub_date')
		app_users = AppUser.objects.all()
		app_user_count = app_users.count()

		context = {"app_user": app_user, "categories": categories,
		 "problems": problems, "solutions": solutions, "app_users": app_users, "app_user_count": app_user_count}
		return render(request, "app_user/index.html", context)




def ProfileView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	categories = Category.objects.all().order_by('-pub_date')
	if request.method == "POST":
		pass


	else:

		context = {"app_user": app_user, "categories": categories}
		return render(request, "app_user/profile.html", context)




def TimelineView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	categories = Category.objects.all().order_by('-pub_date')
	if request.method == "POST":
		pass


	else:
		timeline = []

		context = {"app_user": app_user, "timeline": timeline, "categories": categories}
		return render(request, "app_user/timeline.html", context)




def AddProblemView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	if request.method == "POST":
		
		title = request.POST.get("title")
		detail = request.POST.get("detail")
		category = request.POST.get("category")
		tag = request.POST.get("tag")
		duration = request.POST.get("duration")

		today = timezone.now().date()
		nextD = today + datetime.timedelta(days=int(duration))

		video = request.FILES["video"]
		cover_image = request.FILES["cover_image"]

		

		problem = Problem.objects.create(app_user=app_user, auth_code=app_user.auth_code,
			app_user_name1=app_user.first_name, app_user_name2=app_user.last_name,
			profile_photo=app_user.profile_photo, title=title, detail=detail,
			category=category)

		category = Category.objects.create(name=category, creator=app_user.first_name)
		category.save()

		problem.video = video
		problem.cover_image = cover_image
		problem.app_user = app_user
		problem.switch_date = nextD
		problem.tag1 = tag
		problem.save()



		msg = "Congratulations! Video Uploaded. Kindly wait for approval."
		context = {"app_user": app_user, "msg": msg}
		return render(request, "app_user/notify.html", context)


	else:
		pass





def ProblemDetailView(request, problem_id):
	categories = Category.objects.all().order_by('-pub_date')
	try:
		app_user = AppUser.objects.get(user__pk=request.user.id)

	except:
		app_user = None
		
	if request.method == "POST":

		video = request.FILES["video"]
		
		problem = Problem.objects.get(id=problem_id)
		solution = Solution.objects.create(app_user=app_user, auth_code=app_user.auth_code, app_user_name1=app_user.first_name, app_user_name2=app_user.last_name, profile_photo=app_user.profile_photo, problem=problem, title=problem.title, detail=problem.detail)
		solution.video = video
		solution.save()

		msg = "Congratulations! Video Uploaded. Kindly wait for approval."
		context = {"app_user": app_user, "msg": msg, "categories": categories}
		return render(request, "app_user/notify.html", context)




	else:
		problem = Problem.objects.get(id=problem_id)
		solutions = Solution.objects.filter(problem=problem).order_by('-pub_date')

		context = {"app_user": app_user, "problem": problem, "solutions": solutions, "categories": categories}
		return render(request, "app_user/problem_detail.html", context)




def ProfileView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	categories = Category.objects.all().order_by('-pub_date')
	if request.method == "POST":
		first_name = request.POST.get("first_name")
		last_name = request.POST.get("last_name")
		interest = request.POST.get("interest")


		cover_image = request.FILES["cover_image"]
		profile_photo = request.FILES["profile_photo"]

		app_user.first_name = first_name
		app_user.last_name = last_name
		app_user.interest = interest
		app_user.cover_image = cover_image
		app_user.profile_photo = profile_photo
		app_user.save()


		msg = "Profile data uploaded!"
		context = {"app_user": app_user, "msg": msg, "categories": categories}
		return render(request, "app_user/notify.html", context)





	else:
		problems = Problem.objects.filter(app_user=app_user).order_by('-pub_date')
		solutions = Solution.objects.filter(app_user=app_user).order_by('-pub_date')

		problem_count = problems.count()
		solution_count = solutions.count()

		interests = Category.objects.all().order_by('-pub_date')

app_user/templates/app_user/base.html
{% load static %}
	
	
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    
	<title>ONIONS</title>
	<link rel="stylesheet" href="{% static 'app_user/css/main.min.css'%}">
	<link rel="stylesheet" href="{% static 'app_user/css/style.css'%}">
	<link rel="stylesheet" href="{% static 'app_user/css/color.css'%}">
	
</head>
<body class="full-page">
<div class="row no-gutters vh-100 loader-screen" style="background-color: white;">
    <div class="col align-self-center text-white text-center">
        <img src="https://www.helloonions.com/static/logo1.png" alt="logo">
        {% if app_user %}
        <div class="laoderhorizontal">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
        {% endif %}
    </div>
</div>
<div class="app-layout">
	
	<header class="topbar">
		<div class="back-btn ico-hover" title="Back"><i class="lni lni-angle-double-left"></i></div>
		<div class="top-search ico-hover" title="Search"><i class="lni lni-search-alt"></i></div>
		<div class="logo-place"><a href="#" title=""><img src="images/logo.png" alt=""></a></div>
		{% if app_user %}
		<div class="ac-settings ico-hover" title="Settings"><i class="lni lni-radio-button"></i></div>
		{% endif %}
		<div class="new-post ico-hover" title="Create New Post"><i class="lni lni-plus"></i></div>
	</header>

	<div class="bottom-header">
	    {% if app_user %}
		<ul class="menu-left">
			<li><a class="ico-hover" href="{% url 'app_user:index' %}" title=""><i class="lni lni-home"></i></a></li>
			<li><a class="ico-hover" href="{% url 'app_user:notifications' %}" title=""><i class="lni lni-alarm"></i></a><span>3</span></li>
		</ul>
		<div id="nav-icon2" class="menu-button">
			<span></span>
			<span></span>
			<span></span>
			<span></span>
			<span></span>
			<span></span>
		</div>
		<ul class="menu-right">
			<li><a class="ico-hover" href="{% url 'app_user:timeline' %}" title=""><i class="lni lni-comments"></i></a></li>
			<li class=""><a class="ico-hover" href="{% url 'app_user:profile' %}" title=""><i class="lni lni-user"></i></a></li>
		</ul>
		{% endif %}
	</div>

	<nav>
	  <ul class="menu">
		  <li data-text="Home"><a href="{% url 'app_user:index' %}" title=""><i><img src="{% static 'app_user/images/svg/home.png' %}" alt=""></i><span>Home</span></a></li>
		  <li data-text="Home"><a href="{% url 'app_user:profile' %}" title=""><i><img src="{% static 'app_user/images/svg/user.png' %}" alt=""></i><span>My Profile</span></a></li>
		   <li data-text="Home"><a href="{% url 'app_user:profile' %}" title=""><i><img src="{% static 'app_user/images/svg/user.png' %}" alt=""></i><span>Notification</span></a></li>
		    <li data-text="Home"><a href="{% url 'app_user:profile' %}" title=""><i><img src="{% static 'app_user/images/svg/user.png' %}" alt=""></i><span>Timeline</span></a></li>
		  
	  </ul>
	</nav><!-- compact nav menu -->

	<section>
		<div class="gap redishs high-opacity">
			<div class="content-bg-wrap" style="height: 80px;"></div>
			<div class="container">
				<div class="row" style="height: 20px;">
					<div class="col-12">
						<div class="head-meta">
							<h5>
							    <a href="{% url 'app_user:index' %}"><img style="margin-top: -40px; height: 100px; width: 100px;" src="https://www.helloonions.com/static/logo1.png"></a></h5>
							<ul class="breadcrumb">
								<li><a href="#" title=""><p style="color: purple; font-size: 15px;">Share Problems. Find Solutions.</p></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	
	<section>
		<div class="gap no-gap">
			<div class="good-day-notification">
				<h4>Hello, {{ app_user.first_name }} {{ app_user.lastname }}</h4>
				<p style="font-size: 15px;">Welcome to the Onions Community.</p>
				<div class="day-icon">
					<img style="width: 60px; height: 60px; border-radius: 100px;" src="{% if app_user %}{{ app_user.profile_photo.url }}{% else %}https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg{% endif %}" alt="">
				</div>
			</div>
		</div>
	</section>

	
	



	{% block content %}


						


	{% endblock %}



	<div class="bottombar">
		<span>&copy;Onions Copyright All rights Reserved 2022</span>
	</div>
    
    {% if app_user %}
	<div class="side-slide">
		<span class="close-btn"><i class="lni lni-cross-circle"></i></span>
		<div class="user-avatar">
			<figure><img style="width: 200px; height: 200px;" src="{{ app_user.profile_photo.url }}" alt=""><span class="status status greenbg"></span></figure>
			<div class="user-options">
				<h5>{{ app_user.first_name }} {{ app_user.first_name }}</h5>
				<a href="{% url 'app_user:profile' %}" title="">view profile</a>
			</div>
		</div>
		<ul>
			<li><a href="{% url 'app_user:index' %}" title=""><i class="lni lni-home"></i>Home</a></li>
			<li><a href="{% url 'app_user:profile' %}" title=""><i class="lni lni-user"></i>Profile</a></li>
			<li><a href="{% url 'app_user:notifications' %}" title=""><i class="lni lni-home"></i>Notification</a></li>
			<li><a href="{% url 'app_user:timeline' %}" title=""><i class="lni lni-home"></i>Timeline</a></li>
			<li><a href="#" title=""><i class="lni lni-power-switch"></i>Logout</a></li>
		</ul>
		<div class="night-mode">
			<i class="lni lni-night"></i>Night Mode 
			<input type="checkbox" hidden="hidden" id="night-mode">
			<label class="switch" for="night-mode"></label>
		</div>
	</div><!-- side panel -->

	<div class="search-post">
		<span class="close-btn"><i class="lni lni-cross-circle"></i></span>
		<div class="search-area">
			<h5 class="main-title">Search By</h5>
			<form method="post">
				<input type="text" placeholder="Search #tag, title, category, etc..">
				<div class="filter-search">
					<div>
						<i class="lni lni-calendar"></i>
						<input type="checkbox" id="event">
  						<label for="event">Title</label>
					</div>
					<div>
						<i class="lni lni-calendar"></i>
						<input type="checkbox" id="event">
  						<label for="event">Category</label>
					</div>
					<div>
						<i class="lni lni-calendar"></i>
						<input type="checkbox" id="event">
  						<label for="event">Tags</label>
					</div>
				</div>
				<button type="submit">Find</button>
			</form>
		</div>
	</div><!-- search -->

	<div class="create-new">
		<div class="post-form">
			<h5>Share your problem</h5>
			<span class="close-btn"><i class="lni lni-cross-circle"></i></span>
			<form class="c-form" method="post" action="{% url 'app_user:add_problem' %}" enctype="multipart/form-data">
				{% csrf_token %}
			<input required class="form-control" type="text" name="title" placeholder="Enter a title">
			<input required class="form-control" type="text" name="tag" placeholder="Tag">
			<textarea required name="detail" placeholder="Enter a brief explanation."></textarea>

 
			<select style="width: 100%;
                			height: 40px;
                  padding: 12px 20px;
                  margin: 8px 0;
                  display: inline-block;
                  border: 1px solid #ccc;
                  border-radius: 4px;
                  box-sizing: border-box;" required name="category" id="category">
				{% for item in categories %}
			  		<option value="{{ item.name }}">{{ item.name }}</option>
			  	{% endfor %}
			</select>
			
			<select style="width: 100%;
                                			height: 40px;
                                  padding: 12px 20px;
                                  margin: 8px 0;
                                  display: inline-block;
                                  border: 1px solid #ccc;
                                  border-radius: 4px;
                                  box-sizing: border-box;" required name="duration" id="duration">
			  	<option value="24">24hrs</option>
			  	<option value="48">48hrs</option>
			  	<option value="72">72hrs</option>
			</select>
				<div class="attachments">
					<ul>
						<li>
							<i class="lni lni-image"></i>
							<label class="fileContainer">
								<input name="cover_image" type="file" accept="image/png, image/gif, image/jpeg">
							</label>
						</li>
						<li>
							<i class="lni lni-video"></i>
							<label class="fileContainer">
								<input name="video" type="file" accept="video/mp4,video/x-m4v,video/*">
							</label>
						</li>
						<li class="more-alt">
							<i class="lni lni-more-alt"></i>
						</li>
					</ul>
					<div class="more-alt-options">
						<ul>
							<li><a href="#" title=""><img src="images/svg/recommend.png" alt="">Ask for Recommendation</a></li>
							<li><a href="#" title=""><img src="images/svg/live.png" alt="">Go Live</a></li>
							<li><a href="#" title=""><img src="images/svg/map-marker.png" alt="">Check in</a></li>
							<li><a href="#" title=""><img src="images/svg/gif.png" alt="">Gif</a></li>
						</ul>
						<ol class="post-to-also">
							<li>
								<input type="checkbox" id="switch0002" /> 
								<label for="switch0002" data-on-label="ON" data-off-label="OFF"></label>
								<i class="lni lni-circle-plus"></i>
								NewsFeed
							</li>
							<li>
								<input type="checkbox" id="switch0003" /> 
								<label for="switch0003" data-on-label="ON" data-off-label="OFF"></label>
								<figure><img src="images/resources/user1.jpg" alt=""></figure>Your Story
							</li>
						</ol>
					</div>
				</div>
				<button type="submit">Upload Problem</button>
			</form>
		</div>
	</div><!-- create new post -->



	<div class="share-wraper">
		<div class="share-options">
			<span class="close-btn"><i class="lni lni-cross-circle"></i></span>
			<h5>Share To!</h5>
			<form method="post">
				<textarea placeholder="Write Something"></textarea>
			</form>
			<ul>
				<li><a href="#" title="">Your Timeline</a></li>
				<li class="friends"><a href="#" title="">To Friends</a></li>
				<li class="socialz"><a href="#" title="">Social Media</a></li>
			</ul>
			<div class="social-media" style="display: none;">
				<ul>
					<li><a class="facebook" href="#" title=""><i class="lni lni-facebook"></i></a></li>
					<li><a class="twitter" href="#" title=""><i class="lni lni-twitter"></i></a></li>
					<li><a class="instagram" href="#" title=""><i class="lni lni-instagram"></i></a></li>
					<li><a class="pinterest" href="#" title=""><i class="lni lni-pinterest"></i></a></li>
					<li><a class="youtube" href="#" title=""><i class="lni lni-youtube"></i></a></li>
					<li><a class="dribble" href="#" title=""><i class="lni lni-dribbble"></i></a></li>
					<li><a class="behance" href="#" title=""><i class="lni lni-behance-original"></i></a></li>
				</ul>
			</div>
			<div class="friends-to" style="display: none;">
				<div class="follow-men">
					<figure><img alt="" src="images/resources/user1.jpg" class="mCS_img_loaded"></figure>
					<div class="follow-meta">
						<h5><a title="" href="#">Jack Carter</a></h5>
						<span>family member</span>
					</div>
					<a title="" href="#">Share</a>
				</div>
				<div class="follow-men">
					<figure><img alt="" src="images/resources/user2.jpg" class="mCS_img_loaded"></figure>
					<div class="follow-meta">
						<h5><a title="" href="#">Xang Ching</a></h5>
						<span>Close Friend</span>
					</div>
					<a title="" href="#">Share</a>
				</div>
				<div class="follow-men">
					<figure><img alt="" src="images/resources/user3.jpg" class="mCS_img_loaded"></figure>
					<div class="follow-meta">
						<h5><a title="" href="#">Emma Watson</a></h5>
						<span>Matul Friend</span>
					</div>
					<a title="" href="#">Share</a>
				</div>
			</div>
			<button class="main-btn" type="submit">Publish</button>
		</div>
	</div>
	
	{% endif %}
	
</div>
	

	<script src="{% static 'app_user/js/main.min.js'%}"></script>
	<script src="{% static 'app_user/js/jquery-stories.js'%}"></script>
	<script src="{% static 'app_user/js/script.js'%}"></script>


	<script>
  // Set the date we're counting down to
  var countDownDate = new Date("{{ problem.switch_date }}").getTime();

  // Update the count down every 1 second
  var x = setInterval(function() {

    // Get today's date and time
    var now = new Date().getTime();


    // Find the distance between now and the count down date
    var distance = countDownDate - now;
    //var distance = "{{ counter }}";

    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);

    document.getElementById("ray_counter").innerHTML = days + "d " + hours + "h "
    + minutes + "m " + seconds + "s ";

    // If the count down is finished, write some text
    if (distance < 0) {
      clearInterval(x);
      document.getElementById("ray_counter").innerHTML = "EXPIRED";
    }
  }, 1000);
</script>

	
</body>
</html>